// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Yxvg8YoNiQb7BtsDFLV0LUcdkUpH3g4',
    appId: '1:275150493362:web:c9e8ab677a90b884d79bab',
    messagingSenderId: '275150493362',
    projectId: 'billingappv2',
    authDomain: 'billingappv2.firebaseapp.com',
    storageBucket: 'billingappv2.firebasestorage.app',
    measurementId: 'G-VRT931T916',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJ8i5YdqixSAyxMGZ_jYFB6GUiDFXiNw',
    appId: '1:275150493362:android:807cce370e8a6776d79bab',
    messagingSenderId: '275150493362',
    projectId: 'billingappv2',
    storageBucket: 'billingappv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zX9MdtriMbxaxQ8qb4nv56kfFI7WGsE',
    appId: '1:275150493362:ios:0fab0fe486680841d79bab',
    messagingSenderId: '275150493362',
    projectId: 'billingappv2',
    storageBucket: 'billingappv2.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );
}
